// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: api/notify/log/notify_log.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      uint32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  uint32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Index     *uint32 `protobuf:"varint,3,opt,name=index,proto3,oneof" json:"index,omitempty"`
	User      *string `protobuf:"bytes,4,opt,name=user,proto3,oneof" json:"user,omitempty"`
	NotifyId  *uint32 `protobuf:"varint,5,opt,name=notifyId,proto3,oneof" json:"notifyId,omitempty"`
	ChannelId *uint32 `protobuf:"varint,6,opt,name=channelId,proto3,oneof" json:"channelId,omitempty"`
}

func (x *ListLogRequest) Reset() {
	*x = ListLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_log_notify_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogRequest) ProtoMessage() {}

func (x *ListLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_log_notify_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogRequest.ProtoReflect.Descriptor instead.
func (*ListLogRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_log_notify_log_proto_rawDescGZIP(), []int{0}
}

func (x *ListLogRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLogRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLogRequest) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *ListLogRequest) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *ListLogRequest) GetNotifyId() uint32 {
	if x != nil && x.NotifyId != nil {
		return *x.NotifyId
	}
	return 0
}

func (x *ListLogRequest) GetChannelId() uint32 {
	if x != nil && x.ChannelId != nil {
		return *x.ChannelId
	}
	return 0
}

type ListLogReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*ListLogReply_Log `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListLogReply) Reset() {
	*x = ListLogReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_log_notify_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogReply) ProtoMessage() {}

func (x *ListLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_log_notify_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogReply.ProtoReflect.Descriptor instead.
func (*ListLogReply) Descriptor() ([]byte, []int) {
	return file_api_notify_log_notify_log_proto_rawDescGZIP(), []int{1}
}

func (x *ListLogReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListLogReply) GetList() []*ListLogReply_Log {
	if x != nil {
		return x.List
	}
	return nil
}

type ListLogReply_Channel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListLogReply_Channel) Reset() {
	*x = ListLogReply_Channel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_log_notify_log_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLogReply_Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogReply_Channel) ProtoMessage() {}

func (x *ListLogReply_Channel) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_log_notify_log_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogReply_Channel.ProtoReflect.Descriptor instead.
func (*ListLogReply_Channel) Descriptor() ([]byte, []int) {
	return file_api_notify_log_notify_log_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListLogReply_Channel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListLogReply_Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListLogReply_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListLogReply_Notify) Reset() {
	*x = ListLogReply_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_log_notify_log_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLogReply_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogReply_Notify) ProtoMessage() {}

func (x *ListLogReply_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_log_notify_log_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogReply_Notify.ProtoReflect.Descriptor instead.
func (*ListLogReply_Notify) Descriptor() ([]byte, []int) {
	return file_api_notify_log_notify_log_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ListLogReply_Notify) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListLogReply_Notify) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListLogReply_Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NotifyId   uint32                `protobuf:"varint,2,opt,name=notifyId,proto3" json:"notifyId,omitempty"`
	ChannelId  uint32                `protobuf:"varint,3,opt,name=channelId,proto3" json:"channelId,omitempty"`
	User       string                `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Content    string                `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	FromServer string                `protobuf:"bytes,6,opt,name=fromServer,proto3" json:"fromServer,omitempty"`
	FromIp     string                `protobuf:"bytes,7,opt,name=fromIp,proto3" json:"fromIp,omitempty"`
	Status     bool                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Reason     string                `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt  uint32                `protobuf:"varint,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt  uint32                `protobuf:"varint,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Channel    *ListLogReply_Channel `protobuf:"bytes,12,opt,name=channel,proto3" json:"channel,omitempty"`
	Notify     *ListLogReply_Notify  `protobuf:"bytes,13,opt,name=notify,proto3" json:"notify,omitempty"`
}

func (x *ListLogReply_Log) Reset() {
	*x = ListLogReply_Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_log_notify_log_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLogReply_Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogReply_Log) ProtoMessage() {}

func (x *ListLogReply_Log) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_log_notify_log_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogReply_Log.ProtoReflect.Descriptor instead.
func (*ListLogReply_Log) Descriptor() ([]byte, []int) {
	return file_api_notify_log_notify_log_proto_rawDescGZIP(), []int{1, 2}
}

func (x *ListLogReply_Log) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListLogReply_Log) GetNotifyId() uint32 {
	if x != nil {
		return x.NotifyId
	}
	return 0
}

func (x *ListLogReply_Log) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ListLogReply_Log) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ListLogReply_Log) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ListLogReply_Log) GetFromServer() string {
	if x != nil {
		return x.FromServer
	}
	return ""
}

func (x *ListLogReply_Log) GetFromIp() string {
	if x != nil {
		return x.FromIp
	}
	return ""
}

func (x *ListLogReply_Log) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ListLogReply_Log) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ListLogReply_Log) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListLogReply_Log) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ListLogReply_Log) GetChannel() *ListLogReply_Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *ListLogReply_Log) GetNotify() *ListLogReply_Notify {
	if x != nil {
		return x.Notify
	}
	return nil
}

var File_api_notify_log_notify_log_proto protoreflect.FileDescriptor

var file_api_notify_log_notify_log_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x6c, 0x6f, 0x67,
	0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x18, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfa, 0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x32, 0x28,
	0x01, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12,
	0x1f, 0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x02, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x21, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x48, 0x03, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x49, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49,
	0x64, 0x22, 0xf6, 0x04, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x3e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4c,
	0x6f, 0x67, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x2d, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x2c, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0xb2, 0x03, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x70, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x48, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x6c,
	0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x12, 0x45, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x42, 0x31, 0x0a, 0x18, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x56, 0x31, 0x50, 0x01, 0x5a, 0x07, 0x2e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_notify_log_notify_log_proto_rawDescOnce sync.Once
	file_api_notify_log_notify_log_proto_rawDescData = file_api_notify_log_notify_log_proto_rawDesc
)

func file_api_notify_log_notify_log_proto_rawDescGZIP() []byte {
	file_api_notify_log_notify_log_proto_rawDescOnce.Do(func() {
		file_api_notify_log_notify_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_notify_log_notify_log_proto_rawDescData)
	})
	return file_api_notify_log_notify_log_proto_rawDescData
}

var file_api_notify_log_notify_log_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_notify_log_notify_log_proto_goTypes = []interface{}{
	(*ListLogRequest)(nil),       // 0: notify.api.notify.log.v1.ListLogRequest
	(*ListLogReply)(nil),         // 1: notify.api.notify.log.v1.ListLogReply
	(*ListLogReply_Channel)(nil), // 2: notify.api.notify.log.v1.ListLogReply.Channel
	(*ListLogReply_Notify)(nil),  // 3: notify.api.notify.log.v1.ListLogReply.Notify
	(*ListLogReply_Log)(nil),     // 4: notify.api.notify.log.v1.ListLogReply.Log
}
var file_api_notify_log_notify_log_proto_depIdxs = []int32{
	4, // 0: notify.api.notify.log.v1.ListLogReply.list:type_name -> notify.api.notify.log.v1.ListLogReply.Log
	2, // 1: notify.api.notify.log.v1.ListLogReply.Log.channel:type_name -> notify.api.notify.log.v1.ListLogReply.Channel
	3, // 2: notify.api.notify.log.v1.ListLogReply.Log.notify:type_name -> notify.api.notify.log.v1.ListLogReply.Notify
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_notify_log_notify_log_proto_init() }
func file_api_notify_log_notify_log_proto_init() {
	if File_api_notify_log_notify_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_notify_log_notify_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_log_notify_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLogReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_log_notify_log_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLogReply_Channel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_log_notify_log_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLogReply_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_log_notify_log_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLogReply_Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_notify_log_notify_log_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_notify_log_notify_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notify_log_notify_log_proto_goTypes,
		DependencyIndexes: file_api_notify_log_notify_log_proto_depIdxs,
		MessageInfos:      file_api_notify_log_notify_log_proto_msgTypes,
	}.Build()
	File_api_notify_log_notify_log_proto = out.File
	file_api_notify_log_notify_log_proto_rawDesc = nil
	file_api_notify_log_notify_log_proto_goTypes = nil
	file_api_notify_log_notify_log_proto_depIdxs = nil
}
