// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: api/notify/channel/notify_channel.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListChannelTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListChannelTypeRequest) Reset() {
	*x = ListChannelTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChannelTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelTypeRequest) ProtoMessage() {}

func (x *ListChannelTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelTypeRequest.ProtoReflect.Descriptor instead.
func (*ListChannelTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{0}
}

type ListChannelTypeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ListChannelTypeReply_Type `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListChannelTypeReply) Reset() {
	*x = ListChannelTypeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChannelTypeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelTypeReply) ProtoMessage() {}

func (x *ListChannelTypeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelTypeReply.ProtoReflect.Descriptor instead.
func (*ListChannelTypeReply) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{1}
}

func (x *ListChannelTypeReply) GetList() []*ListChannelTypeReply_Type {
	if x != nil {
		return x.List
	}
	return nil
}

type ListChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Type     *string `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Name     *string `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Status   *bool   `protobuf:"varint,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
}

func (x *ListChannelRequest) Reset() {
	*x = ListChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelRequest) ProtoMessage() {}

func (x *ListChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelRequest.ProtoReflect.Descriptor instead.
func (*ListChannelRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{2}
}

func (x *ListChannelRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListChannelRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListChannelRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ListChannelRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListChannelRequest) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

type ListChannelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*ListChannelReply_Channel `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListChannelReply) Reset() {
	*x = ListChannelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChannelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelReply) ProtoMessage() {}

func (x *ListChannelReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelReply.ProtoReflect.Descriptor instead.
func (*ListChannelReply) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{3}
}

func (x *ListChannelReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListChannelReply) GetList() []*ListChannelReply_Channel {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status *bool   `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Ak     *string `protobuf:"bytes,4,opt,name=ak,proto3,oneof" json:"ak,omitempty"`
	Sk     *string `protobuf:"bytes,5,opt,name=sk,proto3,oneof" json:"sk,omitempty"`
	Extra  *string `protobuf:"bytes,6,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{4}
}

func (x *CreateChannelRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChannelRequest) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

func (x *CreateChannelRequest) GetAk() string {
	if x != nil && x.Ak != nil {
		return *x.Ak
	}
	return ""
}

func (x *CreateChannelRequest) GetSk() string {
	if x != nil && x.Sk != nil {
		return *x.Sk
	}
	return ""
}

func (x *CreateChannelRequest) GetExtra() string {
	if x != nil && x.Extra != nil {
		return *x.Extra
	}
	return ""
}

type CreateChannelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateChannelReply) Reset() {
	*x = CreateChannelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChannelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelReply) ProtoMessage() {}

func (x *CreateChannelReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelReply.ProtoReflect.Descriptor instead.
func (*CreateChannelReply) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{5}
}

func (x *CreateChannelReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type   string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name   string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status *bool   `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Ak     *string `protobuf:"bytes,5,opt,name=ak,proto3,oneof" json:"ak,omitempty"`
	Sk     *string `protobuf:"bytes,6,opt,name=sk,proto3,oneof" json:"sk,omitempty"`
	Extra  *string `protobuf:"bytes,7,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
}

func (x *UpdateChannelRequest) Reset() {
	*x = UpdateChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelRequest) ProtoMessage() {}

func (x *UpdateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelRequest.ProtoReflect.Descriptor instead.
func (*UpdateChannelRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateChannelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateChannelRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateChannelRequest) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

func (x *UpdateChannelRequest) GetAk() string {
	if x != nil && x.Ak != nil {
		return *x.Ak
	}
	return ""
}

func (x *UpdateChannelRequest) GetSk() string {
	if x != nil && x.Sk != nil {
		return *x.Sk
	}
	return ""
}

func (x *UpdateChannelRequest) GetExtra() string {
	if x != nil && x.Extra != nil {
		return *x.Extra
	}
	return ""
}

type UpdateChannelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateChannelReply) Reset() {
	*x = UpdateChannelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateChannelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelReply) ProtoMessage() {}

func (x *UpdateChannelReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelReply.ProtoReflect.Descriptor instead.
func (*UpdateChannelReply) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{7}
}

type DeleteChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteChannelRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteChannelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteChannelReply) Reset() {
	*x = DeleteChannelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChannelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelReply) ProtoMessage() {}

func (x *DeleteChannelReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelReply.ProtoReflect.Descriptor instead.
func (*DeleteChannelReply) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{9}
}

type ListOfficialTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListOfficialTemplateRequest) Reset() {
	*x = ListOfficialTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfficialTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfficialTemplateRequest) ProtoMessage() {}

func (x *ListOfficialTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfficialTemplateRequest.ProtoReflect.Descriptor instead.
func (*ListOfficialTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{10}
}

func (x *ListOfficialTemplateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListOfficialTemplateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ListOfficialTemplateReply_Template `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListOfficialTemplateReply) Reset() {
	*x = ListOfficialTemplateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfficialTemplateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfficialTemplateReply) ProtoMessage() {}

func (x *ListOfficialTemplateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfficialTemplateReply.ProtoReflect.Descriptor instead.
func (*ListOfficialTemplateReply) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{11}
}

func (x *ListOfficialTemplateReply) GetList() []*ListOfficialTemplateReply_Template {
	if x != nil {
		return x.List
	}
	return nil
}

type ListChannelTypeReply_Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListChannelTypeReply_Type) Reset() {
	*x = ListChannelTypeReply_Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChannelTypeReply_Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelTypeReply_Type) ProtoMessage() {}

func (x *ListChannelTypeReply_Type) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelTypeReply_Type.ProtoReflect.Descriptor instead.
func (*ListChannelTypeReply_Type) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListChannelTypeReply_Type) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListChannelTypeReply_Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListChannelReply_Channel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type      string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name      string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Ak        *string `protobuf:"bytes,4,opt,name=ak,proto3,oneof" json:"ak,omitempty"`
	Sk        *string `protobuf:"bytes,5,opt,name=sk,proto3,oneof" json:"sk,omitempty"`
	Extra     *string `protobuf:"bytes,6,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	Status    *bool   `protobuf:"varint,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	CreatedAt uint32  `protobuf:"varint,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt uint32  `protobuf:"varint,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *ListChannelReply_Channel) Reset() {
	*x = ListChannelReply_Channel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChannelReply_Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelReply_Channel) ProtoMessage() {}

func (x *ListChannelReply_Channel) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelReply_Channel.ProtoReflect.Descriptor instead.
func (*ListChannelReply_Channel) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListChannelReply_Channel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListChannelReply_Channel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListChannelReply_Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListChannelReply_Channel) GetAk() string {
	if x != nil && x.Ak != nil {
		return *x.Ak
	}
	return ""
}

func (x *ListChannelReply_Channel) GetSk() string {
	if x != nil && x.Sk != nil {
		return *x.Sk
	}
	return ""
}

func (x *ListChannelReply_Channel) GetExtra() string {
	if x != nil && x.Extra != nil {
		return *x.Extra
	}
	return ""
}

func (x *ListChannelReply_Channel) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

func (x *ListChannelReply_Channel) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListChannelReply_Channel) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListOfficialTemplateReply_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value   string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Color   string `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *ListOfficialTemplateReply_Field) Reset() {
	*x = ListOfficialTemplateReply_Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfficialTemplateReply_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfficialTemplateReply_Field) ProtoMessage() {}

func (x *ListOfficialTemplateReply_Field) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfficialTemplateReply_Field.ProtoReflect.Descriptor instead.
func (*ListOfficialTemplateReply_Field) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ListOfficialTemplateReply_Field) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListOfficialTemplateReply_Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListOfficialTemplateReply_Field) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ListOfficialTemplateReply_Field) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type ListOfficialTemplateReply_Template struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId string                             `protobuf:"bytes,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Title      string                             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Fields     []*ListOfficialTemplateReply_Field `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ListOfficialTemplateReply_Template) Reset() {
	*x = ListOfficialTemplateReply_Template{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_channel_notify_channel_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfficialTemplateReply_Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfficialTemplateReply_Template) ProtoMessage() {}

func (x *ListOfficialTemplateReply_Template) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_channel_notify_channel_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfficialTemplateReply_Template.ProtoReflect.Descriptor instead.
func (*ListOfficialTemplateReply_Template) Descriptor() ([]byte, []int) {
	return file_api_notify_channel_notify_channel_proto_rawDescGZIP(), []int{11, 1}
}

func (x *ListOfficialTemplateReply_Template) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *ListOfficialTemplateReply_Template) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListOfficialTemplateReply_Template) GetFields() []*ListOfficialTemplateReply_Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_api_notify_channel_notify_channel_proto protoreflect.FileDescriptor

var file_api_notify_channel_notify_channel_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x18, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x99, 0x01, 0x0a, 0x14, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x4b, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x37, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x1a, 0x34, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xc4, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x2a, 0x02, 0x28, 0x01, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42,
	0x06, 0x2a, 0x04, 0x18, 0x32, 0x28, 0x01, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xf9, 0x02,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x4a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x1a, 0x82, 0x02, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x13, 0x0a, 0x02, 0x61, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x61, 0x6b, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a,
	0x02, 0x73, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x02, 0x73, 0x6b, 0x88,
	0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x02, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x48, 0x03, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x61, 0x6b, 0x42, 0x05, 0x0a,
	0x03, 0x5f, 0x73, 0x6b, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xd5, 0x01, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x61, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x02, 0x61, 0x6b, 0x88, 0x01, 0x01, 0x12, 0x13,
	0x0a, 0x02, 0x73, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x02, 0x73, 0x6b,
	0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x88, 0x01, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x61, 0x6b,
	0x42, 0x05, 0x0a, 0x03, 0x5f, 0x73, 0x6b, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0xdc, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x13,
	0x0a, 0x02, 0x61, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x02, 0x61, 0x6b,
	0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x73, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x02, 0x52, 0x02, 0x73, 0x6b, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x05,
	0x0a, 0x03, 0x5f, 0x61, 0x6b, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x73, 0x6b, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2f, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x14, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x36, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63,
	0x69, 0x61, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0xee, 0x02, 0x0a, 0x19,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63,
	0x69, 0x61, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a,
	0x61, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x1a, 0x97, 0x01, 0x0a, 0x08, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x55, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61,
	0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x42, 0x34, 0x0a, 0x1c,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x07, 0x2e, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_notify_channel_notify_channel_proto_rawDescOnce sync.Once
	file_api_notify_channel_notify_channel_proto_rawDescData = file_api_notify_channel_notify_channel_proto_rawDesc
)

func file_api_notify_channel_notify_channel_proto_rawDescGZIP() []byte {
	file_api_notify_channel_notify_channel_proto_rawDescOnce.Do(func() {
		file_api_notify_channel_notify_channel_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_notify_channel_notify_channel_proto_rawDescData)
	})
	return file_api_notify_channel_notify_channel_proto_rawDescData
}

var file_api_notify_channel_notify_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_notify_channel_notify_channel_proto_goTypes = []interface{}{
	(*ListChannelTypeRequest)(nil),             // 0: notify.api.notify.channel.v1.ListChannelTypeRequest
	(*ListChannelTypeReply)(nil),               // 1: notify.api.notify.channel.v1.ListChannelTypeReply
	(*ListChannelRequest)(nil),                 // 2: notify.api.notify.channel.v1.ListChannelRequest
	(*ListChannelReply)(nil),                   // 3: notify.api.notify.channel.v1.ListChannelReply
	(*CreateChannelRequest)(nil),               // 4: notify.api.notify.channel.v1.CreateChannelRequest
	(*CreateChannelReply)(nil),                 // 5: notify.api.notify.channel.v1.CreateChannelReply
	(*UpdateChannelRequest)(nil),               // 6: notify.api.notify.channel.v1.UpdateChannelRequest
	(*UpdateChannelReply)(nil),                 // 7: notify.api.notify.channel.v1.UpdateChannelReply
	(*DeleteChannelRequest)(nil),               // 8: notify.api.notify.channel.v1.DeleteChannelRequest
	(*DeleteChannelReply)(nil),                 // 9: notify.api.notify.channel.v1.DeleteChannelReply
	(*ListOfficialTemplateRequest)(nil),        // 10: notify.api.notify.channel.v1.ListOfficialTemplateRequest
	(*ListOfficialTemplateReply)(nil),          // 11: notify.api.notify.channel.v1.ListOfficialTemplateReply
	(*ListChannelTypeReply_Type)(nil),          // 12: notify.api.notify.channel.v1.ListChannelTypeReply.Type
	(*ListChannelReply_Channel)(nil),           // 13: notify.api.notify.channel.v1.ListChannelReply.Channel
	(*ListOfficialTemplateReply_Field)(nil),    // 14: notify.api.notify.channel.v1.ListOfficialTemplateReply.Field
	(*ListOfficialTemplateReply_Template)(nil), // 15: notify.api.notify.channel.v1.ListOfficialTemplateReply.Template
}
var file_api_notify_channel_notify_channel_proto_depIdxs = []int32{
	12, // 0: notify.api.notify.channel.v1.ListChannelTypeReply.list:type_name -> notify.api.notify.channel.v1.ListChannelTypeReply.Type
	13, // 1: notify.api.notify.channel.v1.ListChannelReply.list:type_name -> notify.api.notify.channel.v1.ListChannelReply.Channel
	15, // 2: notify.api.notify.channel.v1.ListOfficialTemplateReply.list:type_name -> notify.api.notify.channel.v1.ListOfficialTemplateReply.Template
	14, // 3: notify.api.notify.channel.v1.ListOfficialTemplateReply.Template.fields:type_name -> notify.api.notify.channel.v1.ListOfficialTemplateReply.Field
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_notify_channel_notify_channel_proto_init() }
func file_api_notify_channel_notify_channel_proto_init() {
	if File_api_notify_channel_notify_channel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_notify_channel_notify_channel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChannelTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChannelTypeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChannelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChannelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateChannelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChannelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfficialTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfficialTemplateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChannelTypeReply_Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChannelReply_Channel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfficialTemplateReply_Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_channel_notify_channel_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfficialTemplateReply_Template); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_notify_channel_notify_channel_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_api_notify_channel_notify_channel_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_api_notify_channel_notify_channel_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_api_notify_channel_notify_channel_proto_msgTypes[13].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_notify_channel_notify_channel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notify_channel_notify_channel_proto_goTypes,
		DependencyIndexes: file_api_notify_channel_notify_channel_proto_depIdxs,
		MessageInfos:      file_api_notify_channel_notify_channel_proto_msgTypes,
	}.Build()
	File_api_notify_channel_notify_channel_proto = out.File
	file_api_notify_channel_notify_channel_proto_rawDesc = nil
	file_api_notify_channel_notify_channel_proto_goTypes = nil
	file_api_notify_channel_notify_channel_proto_depIdxs = nil
}
