// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: api/notify/notify/notify_notify.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       uint32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize   uint32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	CategoryId *uint32 `protobuf:"varint,3,opt,name=categoryId,proto3,oneof" json:"categoryId,omitempty"`
	Status     *string `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Name       *string `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Keyword    *string `protobuf:"bytes,6,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
}

func (x *ListNotifyRequest) Reset() {
	*x = ListNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifyRequest) ProtoMessage() {}

func (x *ListNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifyRequest.ProtoReflect.Descriptor instead.
func (*ListNotifyRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_proto_rawDescGZIP(), []int{0}
}

func (x *ListNotifyRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotifyRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNotifyRequest) GetCategoryId() uint32 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *ListNotifyRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListNotifyRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListNotifyRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

type ListNotifyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*ListNotifyReply_Notify `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListNotifyReply) Reset() {
	*x = ListNotifyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifyReply) ProtoMessage() {}

func (x *ListNotifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifyReply.ProtoReflect.Descriptor instead.
func (*ListNotifyReply) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotifyReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListNotifyReply) GetList() []*ListNotifyReply_Notify {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryId  uint32   `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Keyword     string   `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name        string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Title       string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Variable    []string `protobuf:"bytes,5,rep,name=variable,proto3" json:"variable,omitempty"`
	SendMode    string   `protobuf:"bytes,6,opt,name=sendMode,proto3" json:"sendMode,omitempty"`
	IsTimely    *bool    `protobuf:"varint,7,opt,name=isTimely,proto3,oneof" json:"isTimely,omitempty"`
	Expire      *uint32  `protobuf:"varint,8,opt,name=expire,proto3,oneof" json:"expire,omitempty"`
	Cache       *uint32  `protobuf:"varint,9,opt,name=cache,proto3,oneof" json:"cache,omitempty"`
	Description string   `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateNotifyRequest) Reset() {
	*x = CreateNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotifyRequest) ProtoMessage() {}

func (x *CreateNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotifyRequest.ProtoReflect.Descriptor instead.
func (*CreateNotifyRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNotifyRequest) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateNotifyRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *CreateNotifyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNotifyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNotifyRequest) GetVariable() []string {
	if x != nil {
		return x.Variable
	}
	return nil
}

func (x *CreateNotifyRequest) GetSendMode() string {
	if x != nil {
		return x.SendMode
	}
	return ""
}

func (x *CreateNotifyRequest) GetIsTimely() bool {
	if x != nil && x.IsTimely != nil {
		return *x.IsTimely
	}
	return false
}

func (x *CreateNotifyRequest) GetExpire() uint32 {
	if x != nil && x.Expire != nil {
		return *x.Expire
	}
	return 0
}

func (x *CreateNotifyRequest) GetCache() uint32 {
	if x != nil && x.Cache != nil {
		return *x.Cache
	}
	return 0
}

func (x *CreateNotifyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateNotifyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateNotifyReply) Reset() {
	*x = CreateNotifyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNotifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotifyReply) ProtoMessage() {}

func (x *CreateNotifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotifyReply.ProtoReflect.Descriptor instead.
func (*CreateNotifyReply) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNotifyReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId  uint32   `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Keyword     string   `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name        string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Title       string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Status      *bool    `protobuf:"varint,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Variable    []string `protobuf:"bytes,7,rep,name=variable,proto3" json:"variable,omitempty"`
	SendMode    string   `protobuf:"bytes,8,opt,name=sendMode,proto3" json:"sendMode,omitempty"`
	IsTimely    *bool    `protobuf:"varint,9,opt,name=isTimely,proto3,oneof" json:"isTimely,omitempty"`
	Expire      *uint32  `protobuf:"varint,10,opt,name=expire,proto3,oneof" json:"expire,omitempty"`
	Cache       *uint32  `protobuf:"varint,11,opt,name=cache,proto3,oneof" json:"cache,omitempty"`
	Description string   `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *UpdateNotifyRequest) Reset() {
	*x = UpdateNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotifyRequest) ProtoMessage() {}

func (x *UpdateNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotifyRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotifyRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNotifyRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNotifyRequest) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateNotifyRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *UpdateNotifyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNotifyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNotifyRequest) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

func (x *UpdateNotifyRequest) GetVariable() []string {
	if x != nil {
		return x.Variable
	}
	return nil
}

func (x *UpdateNotifyRequest) GetSendMode() string {
	if x != nil {
		return x.SendMode
	}
	return ""
}

func (x *UpdateNotifyRequest) GetIsTimely() bool {
	if x != nil && x.IsTimely != nil {
		return *x.IsTimely
	}
	return false
}

func (x *UpdateNotifyRequest) GetExpire() uint32 {
	if x != nil && x.Expire != nil {
		return *x.Expire
	}
	return 0
}

func (x *UpdateNotifyRequest) GetCache() uint32 {
	if x != nil && x.Cache != nil {
		return *x.Cache
	}
	return 0
}

func (x *UpdateNotifyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateNotifyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateNotifyReply) Reset() {
	*x = UpdateNotifyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNotifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotifyReply) ProtoMessage() {}

func (x *UpdateNotifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotifyReply.ProtoReflect.Descriptor instead.
func (*UpdateNotifyReply) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_proto_rawDescGZIP(), []int{5}
}

type DeleteNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteNotifyRequest) Reset() {
	*x = DeleteNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotifyRequest) ProtoMessage() {}

func (x *DeleteNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotifyRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotifyRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNotifyRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteNotifyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteNotifyReply) Reset() {
	*x = DeleteNotifyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNotifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotifyReply) ProtoMessage() {}

func (x *DeleteNotifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotifyReply.ProtoReflect.Descriptor instead.
func (*DeleteNotifyReply) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_proto_rawDescGZIP(), []int{7}
}

type ListNotifyReply_Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32                           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId  uint32                           `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Keyword     string                           `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name        string                           `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Title       string                           `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Status      *bool                            `protobuf:"varint,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Variable    []string                         `protobuf:"bytes,7,rep,name=variable,proto3" json:"variable,omitempty"`
	SendMode    string                           `protobuf:"bytes,8,opt,name=sendMode,proto3" json:"sendMode,omitempty"`
	IsTimely    *bool                            `protobuf:"varint,9,opt,name=isTimely,proto3,oneof" json:"isTimely,omitempty"`
	Expire      *uint32                          `protobuf:"varint,10,opt,name=expire,proto3,oneof" json:"expire,omitempty"`
	Cache       *uint32                          `protobuf:"varint,11,opt,name=cache,proto3,oneof" json:"cache,omitempty"`
	Description string                           `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   uint32                           `protobuf:"varint,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt   uint32                           `protobuf:"varint,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Category    *ListNotifyReply_Notify_Category `protobuf:"bytes,15,opt,name=category,proto3,oneof" json:"category,omitempty"`
}

func (x *ListNotifyReply_Notify) Reset() {
	*x = ListNotifyReply_Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotifyReply_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifyReply_Notify) ProtoMessage() {}

func (x *ListNotifyReply_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifyReply_Notify.ProtoReflect.Descriptor instead.
func (*ListNotifyReply_Notify) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListNotifyReply_Notify) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListNotifyReply_Notify) GetCategoryId() uint32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListNotifyReply_Notify) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListNotifyReply_Notify) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListNotifyReply_Notify) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListNotifyReply_Notify) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

func (x *ListNotifyReply_Notify) GetVariable() []string {
	if x != nil {
		return x.Variable
	}
	return nil
}

func (x *ListNotifyReply_Notify) GetSendMode() string {
	if x != nil {
		return x.SendMode
	}
	return ""
}

func (x *ListNotifyReply_Notify) GetIsTimely() bool {
	if x != nil && x.IsTimely != nil {
		return *x.IsTimely
	}
	return false
}

func (x *ListNotifyReply_Notify) GetExpire() uint32 {
	if x != nil && x.Expire != nil {
		return *x.Expire
	}
	return 0
}

func (x *ListNotifyReply_Notify) GetCache() uint32 {
	if x != nil && x.Cache != nil {
		return *x.Cache
	}
	return 0
}

func (x *ListNotifyReply_Notify) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListNotifyReply_Notify) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListNotifyReply_Notify) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ListNotifyReply_Notify) GetCategory() *ListNotifyReply_Notify_Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type ListNotifyReply_Notify_Category struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListNotifyReply_Notify_Category) Reset() {
	*x = ListNotifyReply_Notify_Category{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotifyReply_Notify_Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifyReply_Notify_Category) ProtoMessage() {}

func (x *ListNotifyReply_Notify_Category) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifyReply_Notify_Category.ProtoReflect.Descriptor instead.
func (*ListNotifyReply_Notify_Category) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *ListNotifyReply_Notify_Category) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListNotifyReply_Notify_Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_notify_notify_notify_notify_proto protoreflect.FileDescriptor

var file_api_notify_notify_notify_notify_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x02,
	0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x25, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x32, 0x28, 0x01, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x23, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x88, 0x01,
	0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0xc4, 0x05, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x47, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x1a, 0xd1, 0x04, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x1a, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x69, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x6c, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x08, 0x69, 0x73, 0x54,
	0x69, 0x6d, 0x65, 0x6c, 0x79, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x02, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0d, 0x48, 0x03, 0x52, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x5d,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x3c, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x48, 0x04,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x88, 0x01, 0x01, 0x1a, 0x2e, 0x0a,
	0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x69, 0x73, 0x54,
	0x69, 0x6d, 0x65, 0x6c, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0xce, 0x02, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x69,
	0x73, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x08, 0x69, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x79, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x06,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x02, 0x52, 0x05, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x69, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x6c, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8f, 0x03,
	0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x1a, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x65, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x69, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x6c, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x08, 0x69, 0x73, 0x54,
	0x69, 0x6d, 0x65, 0x6c, 0x79, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x02, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0d, 0x48, 0x03, 0x52, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x69, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x22,
	0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x2e, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x32, 0x0a, 0x1b, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x42, 0x08, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x56, 0x31, 0x50, 0x01, 0x5a, 0x07, 0x2e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_notify_notify_notify_notify_proto_rawDescOnce sync.Once
	file_api_notify_notify_notify_notify_proto_rawDescData = file_api_notify_notify_notify_notify_proto_rawDesc
)

func file_api_notify_notify_notify_notify_proto_rawDescGZIP() []byte {
	file_api_notify_notify_notify_notify_proto_rawDescOnce.Do(func() {
		file_api_notify_notify_notify_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_notify_notify_notify_notify_proto_rawDescData)
	})
	return file_api_notify_notify_notify_notify_proto_rawDescData
}

var file_api_notify_notify_notify_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_notify_notify_notify_notify_proto_goTypes = []interface{}{
	(*ListNotifyRequest)(nil),               // 0: notify.api.notify.notify.v1.ListNotifyRequest
	(*ListNotifyReply)(nil),                 // 1: notify.api.notify.notify.v1.ListNotifyReply
	(*CreateNotifyRequest)(nil),             // 2: notify.api.notify.notify.v1.CreateNotifyRequest
	(*CreateNotifyReply)(nil),               // 3: notify.api.notify.notify.v1.CreateNotifyReply
	(*UpdateNotifyRequest)(nil),             // 4: notify.api.notify.notify.v1.UpdateNotifyRequest
	(*UpdateNotifyReply)(nil),               // 5: notify.api.notify.notify.v1.UpdateNotifyReply
	(*DeleteNotifyRequest)(nil),             // 6: notify.api.notify.notify.v1.DeleteNotifyRequest
	(*DeleteNotifyReply)(nil),               // 7: notify.api.notify.notify.v1.DeleteNotifyReply
	(*ListNotifyReply_Notify)(nil),          // 8: notify.api.notify.notify.v1.ListNotifyReply.Notify
	(*ListNotifyReply_Notify_Category)(nil), // 9: notify.api.notify.notify.v1.ListNotifyReply.Notify.Category
}
var file_api_notify_notify_notify_notify_proto_depIdxs = []int32{
	8, // 0: notify.api.notify.notify.v1.ListNotifyReply.list:type_name -> notify.api.notify.notify.v1.ListNotifyReply.Notify
	9, // 1: notify.api.notify.notify.v1.ListNotifyReply.Notify.category:type_name -> notify.api.notify.notify.v1.ListNotifyReply.Notify.Category
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_notify_notify_notify_notify_proto_init() }
func file_api_notify_notify_notify_notify_proto_init() {
	if File_api_notify_notify_notify_notify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_notify_notify_notify_notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotifyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNotifyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNotifyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNotifyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotifyReply_Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotifyReply_Notify_Category); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_notify_notify_notify_notify_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_api_notify_notify_notify_notify_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_api_notify_notify_notify_notify_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_api_notify_notify_notify_notify_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_notify_notify_notify_notify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notify_notify_notify_notify_proto_goTypes,
		DependencyIndexes: file_api_notify_notify_notify_notify_proto_depIdxs,
		MessageInfos:      file_api_notify_notify_notify_notify_proto_msgTypes,
	}.Build()
	File_api_notify_notify_notify_notify_proto = out.File
	file_api_notify_notify_notify_notify_proto_rawDesc = nil
	file_api_notify_notify_notify_notify_proto_goTypes = nil
	file_api_notify_notify_notify_notify_proto_depIdxs = nil
}
