// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: api/notify/notify/notify_notify_category.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListNotifyCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Name     *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
}

func (x *ListNotifyCategoryRequest) Reset() {
	*x = ListNotifyCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotifyCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifyCategoryRequest) ProtoMessage() {}

func (x *ListNotifyCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifyCategoryRequest.ProtoReflect.Descriptor instead.
func (*ListNotifyCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_category_proto_rawDescGZIP(), []int{0}
}

func (x *ListNotifyCategoryRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotifyCategoryRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNotifyCategoryRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ListNotifyCategoryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*ListNotifyCategoryReply_NotifyCategory `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListNotifyCategoryReply) Reset() {
	*x = ListNotifyCategoryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotifyCategoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifyCategoryReply) ProtoMessage() {}

func (x *ListNotifyCategoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifyCategoryReply.ProtoReflect.Descriptor instead.
func (*ListNotifyCategoryReply) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_category_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotifyCategoryReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListNotifyCategoryReply) GetList() []*ListNotifyCategoryReply_NotifyCategory {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateNotifyCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateNotifyCategoryRequest) Reset() {
	*x = CreateNotifyCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNotifyCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotifyCategoryRequest) ProtoMessage() {}

func (x *CreateNotifyCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotifyCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateNotifyCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_category_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNotifyCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNotifyCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateNotifyCategoryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateNotifyCategoryReply) Reset() {
	*x = CreateNotifyCategoryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNotifyCategoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotifyCategoryReply) ProtoMessage() {}

func (x *CreateNotifyCategoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotifyCategoryReply.ProtoReflect.Descriptor instead.
func (*CreateNotifyCategoryReply) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_category_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNotifyCategoryReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateNotifyCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *UpdateNotifyCategoryRequest) Reset() {
	*x = UpdateNotifyCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNotifyCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotifyCategoryRequest) ProtoMessage() {}

func (x *UpdateNotifyCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotifyCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotifyCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_category_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNotifyCategoryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNotifyCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNotifyCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateNotifyCategoryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateNotifyCategoryReply) Reset() {
	*x = UpdateNotifyCategoryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNotifyCategoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotifyCategoryReply) ProtoMessage() {}

func (x *UpdateNotifyCategoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotifyCategoryReply.ProtoReflect.Descriptor instead.
func (*UpdateNotifyCategoryReply) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_category_proto_rawDescGZIP(), []int{5}
}

type DeleteNotifyCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteNotifyCategoryRequest) Reset() {
	*x = DeleteNotifyCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNotifyCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotifyCategoryRequest) ProtoMessage() {}

func (x *DeleteNotifyCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotifyCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotifyCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_category_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNotifyCategoryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteNotifyCategoryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteNotifyCategoryReply) Reset() {
	*x = DeleteNotifyCategoryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNotifyCategoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotifyCategoryReply) ProtoMessage() {}

func (x *DeleteNotifyCategoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotifyCategoryReply.ProtoReflect.Descriptor instead.
func (*DeleteNotifyCategoryReply) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_category_proto_rawDescGZIP(), []int{7}
}

type ListNotifyCategoryReply_NotifyCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   uint32 `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *ListNotifyCategoryReply_NotifyCategory) Reset() {
	*x = ListNotifyCategoryReply_NotifyCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotifyCategoryReply_NotifyCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifyCategoryReply_NotifyCategory) ProtoMessage() {}

func (x *ListNotifyCategoryReply_NotifyCategory) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_notify_notify_notify_category_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifyCategoryReply_NotifyCategory.ProtoReflect.Descriptor instead.
func (*ListNotifyCategoryReply_NotifyCategory) Descriptor() ([]byte, []int) {
	return file_api_notify_notify_notify_notify_category_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListNotifyCategoryReply_NotifyCategory) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListNotifyCategoryReply_NotifyCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListNotifyCategoryReply_NotifyCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListNotifyCategoryReply_NotifyCategory) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_api_notify_notify_notify_notify_category_proto protoreflect.FileDescriptor

var file_api_notify_notify_notify_notify_category_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1b, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x32, 0x28, 0x01, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xfe, 0x01, 0x0a, 0x17, 0x4c,
	0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x57, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x43, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x74, 0x0a, 0x0e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x65, 0x0a, 0x1b, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10,
	0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x7e, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a,
	0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02,
	0x10, 0x01, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x1b, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x36, 0x0a, 0x1b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x32, 0x0a, 0x1b, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31,
	0x42, 0x08, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x07, 0x2e, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_notify_notify_notify_notify_category_proto_rawDescOnce sync.Once
	file_api_notify_notify_notify_notify_category_proto_rawDescData = file_api_notify_notify_notify_notify_category_proto_rawDesc
)

func file_api_notify_notify_notify_notify_category_proto_rawDescGZIP() []byte {
	file_api_notify_notify_notify_notify_category_proto_rawDescOnce.Do(func() {
		file_api_notify_notify_notify_notify_category_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_notify_notify_notify_notify_category_proto_rawDescData)
	})
	return file_api_notify_notify_notify_notify_category_proto_rawDescData
}

var file_api_notify_notify_notify_notify_category_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_notify_notify_notify_notify_category_proto_goTypes = []interface{}{
	(*ListNotifyCategoryRequest)(nil),              // 0: notify.api.notify.notify.v1.ListNotifyCategoryRequest
	(*ListNotifyCategoryReply)(nil),                // 1: notify.api.notify.notify.v1.ListNotifyCategoryReply
	(*CreateNotifyCategoryRequest)(nil),            // 2: notify.api.notify.notify.v1.CreateNotifyCategoryRequest
	(*CreateNotifyCategoryReply)(nil),              // 3: notify.api.notify.notify.v1.CreateNotifyCategoryReply
	(*UpdateNotifyCategoryRequest)(nil),            // 4: notify.api.notify.notify.v1.UpdateNotifyCategoryRequest
	(*UpdateNotifyCategoryReply)(nil),              // 5: notify.api.notify.notify.v1.UpdateNotifyCategoryReply
	(*DeleteNotifyCategoryRequest)(nil),            // 6: notify.api.notify.notify.v1.DeleteNotifyCategoryRequest
	(*DeleteNotifyCategoryReply)(nil),              // 7: notify.api.notify.notify.v1.DeleteNotifyCategoryReply
	(*ListNotifyCategoryReply_NotifyCategory)(nil), // 8: notify.api.notify.notify.v1.ListNotifyCategoryReply.NotifyCategory
}
var file_api_notify_notify_notify_notify_category_proto_depIdxs = []int32{
	8, // 0: notify.api.notify.notify.v1.ListNotifyCategoryReply.list:type_name -> notify.api.notify.notify.v1.ListNotifyCategoryReply.NotifyCategory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_notify_notify_notify_notify_category_proto_init() }
func file_api_notify_notify_notify_notify_category_proto_init() {
	if File_api_notify_notify_notify_notify_category_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_notify_notify_notify_notify_category_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotifyCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_category_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotifyCategoryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_category_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNotifyCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_category_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNotifyCategoryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_category_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNotifyCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_category_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNotifyCategoryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_category_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNotifyCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_category_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNotifyCategoryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notify_notify_notify_notify_category_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotifyCategoryReply_NotifyCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_notify_notify_notify_notify_category_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_notify_notify_notify_notify_category_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notify_notify_notify_notify_category_proto_goTypes,
		DependencyIndexes: file_api_notify_notify_notify_notify_category_proto_depIdxs,
		MessageInfos:      file_api_notify_notify_notify_notify_category_proto_msgTypes,
	}.Build()
	File_api_notify_notify_notify_notify_category_proto = out.File
	file_api_notify_notify_notify_notify_category_proto_rawDesc = nil
	file_api_notify_notify_notify_notify_category_proto_goTypes = nil
	file_api_notify_notify_notify_notify_category_proto_depIdxs = nil
}
